### ISSUE TITLE
Create new image with latest alpine version and publish it

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/subscription-cleanup-job#19]
**Description**

We have to publish a new image as the last images is more than 1/2 year ago. We should bump also the Alpine + Golang version to the latest one to address Golang issues.

AC:
- [x] Update alpine to latest and security-issue free version
- [x] Release new image for subscription-cleanup job
- [x] Get in touch with @piotrmiskiewicz / @kyma-project/gopher  to clarify how we update this job on KCP landscapes

**Comment by VOID404** [comment]
https://github.com/kyma-project/control-plane/pull/3484
