### ISSUE TITLE
Fix OSS security issues in subscription-cleanup-job repository

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/subscription-cleanup-job#24]
**Description**

We have to ensure that our repositories are properly configured and following SAP security guidelines.

The OSS scanner reported several findings for the subscription-cleanup-job repository which we have to fix asap:

https://github.com/kyma-project/subscription-cleanup-job/issues?q=is%3Aissue+is%3Aopen+OSS

AC:
- [ ] Fixes for the OSS reported issues are applied and no OSS issues are open anymore

**Comment by mvshao** [comment]
The problems with OSS have been fixed and closed. We have to wait a few days for the OSS bot to scan our repository again. If no new errors appear we will be able to close this issue.

**Comment by koala7659** [comment]
It has been checked and we close it
